Corrupt dev tarballs mean we shouldn't use Drush to download Drupal.

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -54,11 +54,20 @@ then
   echo
 
   export
-  if ! $DRUSH_SCRIPT dl drupal --default-major=8 --dev --destination=${OPENSHIFT_DATA_DIR}downloads --yes
+  # Skip this, since d.o dev releases for 8.x seem to be corrupt a lot of the time.
+  #if ! $DRUSH_SCRIPT dl drupal --default-major=8 --dev --destination=${OPENSHIFT_DATA_DIR}downloads --yes
+  if ! wget -O ${OPENSHIFT_DATA_DIR}downloads/drupal.tgz http://ftp.drupal.org/files/projects/drupal-8.x-dev.tar.gz 
   then
-    echo "ERROR: Unable download and install Drupal."
+    echo "ERROR: Unable to download Drupal."
     exit 7
   fi
+
+  if ! tar xzf -C ${OPENSHIFT_DATA_DIR}/downloads ${OPENSHIFT_DATA_DIR}downloads/drupal.tgz 
+  then
+    echo "ERROR: Unable to extract Drupal."
+    exit 12
+  fi
+
   export DRUPAL_INSTALL_DIR="${OPENSHIFT_DATA_DIR}downloads/`ls -1rt ${OPENSHIFT_DATA_DIR}downloads | head -1`"
   ln -s ${DRUPAL_INSTALL_DIR} ${OPENSHIFT_DATA_DIR}downloads/current
 
