Try running drush site-install in the background.

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -63,16 +63,6 @@ then
 
   pushd ${OPENSHIFT_REPO_DIR}php
 
-  echo
-  echo "Creating a new Drupal site at ${DRUPAL_SITE_DIR}/default"
-  echo
-  #if ! $DRUSH_SCRIPT site-install standard --site-name=${OPENSHIFT_APP_NAME} --account-pass=openshift_changeme --db-url=mysql://$OPENSHIFT_MYSQL_DB_USERNAME:$OPENSHIFT_MYSQL_DB_PASSWORD@$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/$OPENSHIFT_APP_NAME --yes
-  #then
-  #  echo "Unable to configure your Drupal installation"
-  #  echo
-  #  exit 10
-  #fi
-
   # Installing 8 is too slow, so instead, make a settings file from default.settings.php.
   if [ ! -f "$DRUPAL_SETTINGS" ]
   then
@@ -124,6 +114,16 @@ END
 
   chmod u-w ${DRUPAL_SETTINGS} ${DRUPAL_SITE_DIR}/default
 
+  echo
+  echo "Creating a new Drupal site at ${DRUPAL_SITE_DIR}/default"
+  echo
+  $DRUSH_SCRIPT site-install standard --site-name=${OPENSHIFT_APP_NAME} --account-pass=openshift_changeme --db-url=mysql://$OPENSHIFT_MYSQL_DB_USERNAME:$OPENSHIFT_MYSQL_DB_PASSWORD@$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/$OPENSHIFT_APP_NAME --yes &
+  #then
+  #  echo "Unable to configure your Drupal installation"
+  #  echo
+  #  exit 10
+  #fi
+
   popd
   echo
   client_result ""
@@ -131,9 +131,6 @@ END
   client_result "Go to http://${OPENSHIFT_APP_DNS}/core/install.php to install Drupal."
   if [ ! -z $OPENSHIFT_MYSQL_DB_PASSWORD ]; then
     client_result "You will need to enter ${OPENSHIFT_MYSQL_DB_PASSWORD} as the MySQL password for the installer."
-  else
-    echo "You will need to add a MySQL cartridge to your application to run Drupal."
-    exit 11
   fi
 else
   echo "Drupal is already configured.  Delete settings.php to rerun setup"
